In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import nltk

%matplotlib inline


In [2]:
datasets = pd.read_csv("/home/shrestha/mPercept/Natural Language Processing/Sentiment Analysis/IMDB reviews/imdb_reviews.csv", delimiter = '\t', quoting = 3, header = None)

                       

In [3]:
datasets.columns = ['reviews', 'Likes']


In [4]:
datasets

reviews  Likes
0    A very, very, very slow-moving, aimless movie ...      0
1    Not sure who was more lost - the flat characte...      0
2    Attempting artiness with black & white and cle...      0
3         Very little music or anything to speak of.        0
4    The best scene in the movie was when Gerardo i...      1
5    The rest of the movie lacks art, charm, meanin...      0
6                                  Wasted two hours.        0
7    Saw the movie today and thought it was a good ...      1
8                                 A bit predictable.        0
9    Loved the casting of Jimmy Buffet as the scien...      1
10                And those baby owls were adorable.        1
11   The movie showed a lot of Florida at it's best...      1
12   The Songs Were The Best And The Muppets Were S...      1
13                                   It Was So Cool.        1
14   This is a very "right on case" movie that deli...      1
15   It had some average acting from the main perso...      0
16   This review is long overdue, since I consider ...      1
17   I'll put this gem up against any movie in term...      1
18   It's practically perfect in all of them – a tr...      1
19   " The structure of this film is easily the mos...      1
20   I can think of no other film where something v...      1
21   In other words, the content level of this film...      1
22   How can anyone in their right mind ask for any...      1
23   It's quite simply the highest, most superlativ...      1
24   Yes, this film does require a rather significa...      1
25       This short film certainly pulls no punches.        0
26   Graphics is far from the best part of the game.        0
27   This is the number one best TH game in the ser...      1
28                          It deserves strong love.        1
29                             It is an insane game.        1
..                                                 ...    ...
970  Enough can not be said of the remarkable anima...      1
971  The art style has the appearance of crayon/pen...      1
972  If you act in such a film, you should be glad ...      0
973  This one wants to surf on the small wave of sp...      0
974  If you haven't choked in your own vomit by the...      0
975  Still, it makes up for all of this with a supe...      1
976  Just consider the excellent story, solid actin...      1
977  Instead, we got a bore fest about a whiny, spo...      0
978  Then I watched it again two Sundays ago (March...      1
979       It is a very well acted and done TV Movie.        1
980  Judith Light is one of my favorite actresses a...      1
981                I keep watching it over and over.        1
982                 It's a sad movie, but very good.        1
983  If you have not seen this movie, I definitely ...      1
984           She is as lovely as usual, this cutie!        1
985  Still it's quite interesting and entertaining ...      1
986                    ;) Recommend with confidence!        1
987  This movie is well-balanced with comedy and dr...      1
988  It was a riot to see Hugo Weaving play a sex-o...      1
989  :) Anyway, the plot flowed smoothly and the ma...      1
990  The opening sequence of this gem is a classic,...      1
991             Fans of the genre will be in heaven.        1
992                Lange had become a great actress.        1
993                It looked like a wonderful story.        1
994            I never walked out of a movie faster.        0
995  I just got bored watching Jessice Lange take h...      0
996  Unfortunately, any virtue in this film's produ...      0
997                   In a word, it is embarrassing.        0
998                               Exceptionally bad!        0
999  All in all its an insult to one's intelligence...      0

[1000 rows x 2 columns]

In [5]:
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [6]:
ps = PorterStemmer() #object initialization for stemmer
word_net_lemmatizer = WordNetLemmatizer() #object initilization for lemmatizer

In [7]:
corpus = [] #Initializing empty list

In [8]:
#Cleaning the text with stemmer
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', datasets['reviews'][i])
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    review = [ps.stem(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
#Cleaning the text with lemmatizer
for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', datasets['reviews'][i])
    review = review.lower()
    review = review.split()
    review = [word for word in review if not word in set(stopwords.words('english'))]
    review = [word_net_lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [9]:
corpus

['slow move aimless movi distress drift young man',
 'sure lost flat charact audienc nearli half walk',
 'attempt arti black white clever camera angl movi disappoint becam even ridicul act poor plot line almost non exist',
 'littl music anyth speak',
 'best scene movi gerardo tri find song keep run head',
 'rest movi lack art charm mean empti work guess empti',
 'wast two hour',
 'saw movi today thought good effort good messag kid',
 'bit predict',
 'love cast jimmi buffet scienc teacher',
 'babi owl ador',
 'movi show lot florida best made look appeal',
 'song best muppet hilari',
 'cool',
 'right case movi deliv everyth almost right face',
 'averag act main person low budget clearli see',
 'review long overdu sinc consid tale two sister singl greatest film ever made',
 'put gem movi term screenplay cinematographi act post product edit direct aspect film make',
 'practic perfect true masterpiec sea faux masterpiec',
 'structur film easili tightli construct histori cinema',
 'think fil

In [10]:
df = pd.DataFrame({'Review':corpus}) #creating a dataframe with column name as review 

In [11]:
df


Review
0      slow move aimless movi distress drift young man
1      sure lost flat charact audienc nearli half walk
2    attempt arti black white clever camera angl mo...
3                              littl music anyth speak
4    best scene movi gerardo tri find song keep run...
5    rest movi lack art charm mean empti work guess...
6                                        wast two hour
7    saw movi today thought good effort good messag...
8                                          bit predict
9                love cast jimmi buffet scienc teacher
10                                       babi owl ador
11         movi show lot florida best made look appeal
12                             song best muppet hilari
13                                                cool
14     right case movi deliv everyth almost right face
15       averag act main person low budget clearli see
16   review long overdu sinc consid tale two sister...
17   put gem movi term screenplay cinematographi ac...
18   practic perfect true masterpiec sea faux maste...
19   structur film easili tightli construct histori...
20    think film someth vital import occur everi minut
21   word content level film enough easili fill doz...
22                     anyon right mind ask anyth movi
23       quit simpli highest superl form cinema imagin
24   ye film requir rather signific amount puzzl so...
25                     short film certainli pull punch
26                          graphic far best part game
27                        number one best th game seri
28                                  deserv strong love
29                                          insan game
..                                                 ...
970                       enough said remark anim film
971  art style appear crayon pencil draw wonder col...
972   act film glad gonna drift away earth far possibl
973  one want surf small wave space movi deep impac...
974  choke vomit end cheap drama worthless dialogu ...
975  still make super end depict great sea vessel t...
976    consid excel stori solid act look film ad bonus
977     instead got bore fest whini spoil brat babysit
978  watch two sunday ago march th began realli enj...
979                              well act done tv movi
980  judith light one favorit actress think superb ...
981                                         keep watch
982                                      sad movi good
983                        seen movi definit recommend
984                                    love usual cuti
985               still quit interest entertain follow
986                                   recommend confid
987     movi well balanc comedi drama thoroughli enjoy
988  riot see hugo weav play sex obsess gay real es...
989     anyway plot flow smoothli male bond scene hoot
990  open sequenc gem classic cat n mous game follo...
991                                    fan genr heaven
992                           lang becom great actress
993                             look like wonder stori
994                             never walk movi faster
995              got bore watch jessic lang take cloth
996  unfortun virtu film product work lost regrett ...
997                                     word embarrass
998                                         except bad
999                insult one intellig huge wast money

[1000 rows x 1 columns]

In [12]:
from sklearn.feature_extraction.text import CountVectorizer


In [13]:
cv = CountVectorizer(max_features = 2300)
fit_corpus = cv.fit(corpus)
print(cv.get_feature_names())

['aailiyah', 'abandon', 'abil', 'abroad', 'absolut', 'abstrus', 'abysm', 'academi', 'accent', 'access', 'acclaim', 'accolad', 'accur', 'accus', 'achiev', 'achil', 'ackerman', 'act', 'action', 'actor', 'actress', 'actual', 'ad', 'adam', 'adapt', 'add', 'addit', 'admin', 'admir', 'admit', 'ador', 'adrift', 'adventur', 'advis', 'aerial', 'aesthet', 'affect', 'affleck', 'afraid', 'africa', 'afternoon', 'age', 'ago', 'agre', 'aimless', 'air', 'akasha', 'akin', 'alert', 'alexand', 'alik', 'allison', 'allow', 'almost', 'along', 'alongsid', 'alreadi', 'also', 'although', 'alway', 'amateurish', 'amaz', 'amazingli', 'america', 'american', 'among', 'amount', 'amus', 'anatomist', 'angel', 'angela', 'angelina', 'angl', 'angri', 'angu', 'anguish', 'anim', 'anita', 'ann', 'anniversari', 'annoy', 'anoth', 'anthoni', 'antithesi', 'anyon', 'anyth', 'anyway', 'apart', 'appal', 'appeal', 'appear', 'applaud', 'applaus', 'appreci', 'appropri', 'apt', 'argu', 'armageddon', 'armand', 'around', 'array', 'art',

In [14]:
transform_corpus = cv.transform(corpus) #X = cv.fit_transform(corpus).toarray()

In [15]:
transform_corpus_toarray = transform_corpus.toarray()

In [16]:
print(transform_corpus_toarray)
print(transform_corpus_toarray.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(1000, 2300)


In [17]:
X = transform_corpus_toarray

In [40]:
save_count_vectorizer = open("count_vectorizer.pickle", "wb")
pickle.dump(cv, save_count_vectorizer)
save_count_vectorizer.close()

In [18]:
X.shape

(1000, 2300)

In [19]:
y = datasets.iloc[:, 1].values


In [20]:
print(y)

[0 0 0 0 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1
 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1
 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 1 1
 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0
 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1
 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 1 1 1 1 1 0 0 1 1 1 

In [21]:
from sklearn.cross_validation import train_test_split

/home/shrestha/anaconda3/envs/abhiyush/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [23]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB


In [24]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [25]:
classifier = MultinomialNB(alpha = 0.1)
classifier.fit(X_train, y_train)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [39]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
y_pred = classifier.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
cm = confusion_matrix(y_test, y_pred)

In [29]:
cm

array([[69, 17],
       [27, 87]])

In [30]:
accuracy = (71+64)/200 *100
print("The accuracy of the Gaussian naive bayes model using stemmer is : ", accuracy)

The accuracy of the Gaussian naive bayes model using stemmer is :  67.5


In [31]:
accuracy = (69+87)/200 *100
print("The accuracy of the model Multinomial naive bayes using stemmer is : ", accuracy)

The accuracy of the model Multinomial naive bayes using stemmer is :  78.0


In [32]:
import pickle


In [33]:
save_classifier = open("naivebayes.pickle", "wb")
pickle.dump(classifier, save_classifier)
save_classifier.close()

In [36]:
open_classifier = open("naivebayes.pickle", "rb")
classifier1 = pickle.load(open_classifier)
open_classifier.close()

In [37]:
y_pred11 = classifier1.predict(X_test)

In [38]:
y_pred

array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0])

In [ ]:
y_pred

In [ ]:
from sklearn.metrics import roc_auc_score, roc_curve


In [ ]:
score = roc_auc_score(y_test, y_pred)
score

In [ ]:
#Spitting the datasets into train and test sets 
a_train, a_test, b_train, b_test = train_test_split(datasets['reviews'][:], datasets['Likes'][:], test_size = 0.20, random_state = 0)

training_sets = pd.DataFrame({'Training_review':a_train})
test_sets = pd.DataFrame({'Test_review' : a_test})

training_sets['Trainig_likes'] = b_train
test_sets['Test_likes'] = b_test

test_sets['Test_likes_predicted'] = y_pred

y_pred_chr = []

for i in range(0,200):
    if y_pred[i] == 0:
        y_pred_chr.append('Bad')
    else:
        y_pred_chr.append('Good')
    

y_pred_chr = pd.DataFrame(y_pred_chr)
test_sets['test_likes_predicted_chr'] = y_pred_chr


In [ ]:
test_sets

# Tf-idf 

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectorizer = TfidfVectorizer().fit(corpus)

In [ ]:
print(tfidf_vectorizer.get_feature_names())

In [ ]:
tfidf_vectorizer_transform = tfidf_vectorizer.transform(a_test)

In [ ]:
print(tfidf_vectorizer_transform.toarray())

In [ ]:
pd.DataFrame(tfidf_vectorizer_transform.toarray(), columns = tfidf_vectorizer.get_feature_names())

# Visualization 

In [ ]:
from nltk import FreqDist
from collections import Counter


In [ ]:
corpus

In [ ]:
#joining each term of the corpus
corpus_combine = ' '.join(corpus)

In [ ]:
type(corpus_combine)

In [ ]:
# simple tokenization
words = corpus_combine.split()
print(words)
frequency_map = Counter(words)

# for scatter plot
indices_max = 200 # max number of points to plot
Y = list(frequency_map.values())[:indices_max]
X = list(range(len(Y)))
words_plot = list(frequency_map.keys())[:indices_max]

In [ ]:
plt.scatter(X,Y)

In [ ]:
fig, ax = plt.subplots()
ax.scatter(X, Y)


In [ ]:
# scatter plot with labelled point
fig, ax = plt.subplots(figsize = (15,15))
ax.scatter(X, Y)

for i, txt in enumerate(words_plot):
    ax.annotate(txt, (X[i],Y[i]))

In [ ]:
# nltk tokenizer and frequency map# nltk  
tokens = nltk.word_tokenize(corpus_combine)
#print(tokens)
freq = FreqDist(tokens)
print(freq['i'])
freq.plot(25, cumulative=False)